// Bingo squares for The Great British Bake Off. Order matters: cards reference squares by index,
// so only append or edit in place while rooms are live; reordering is safe between episodes.
// Soft hyphens (\u00AD) mark break points in long capitalised words, which browsers won't auto-hyphenate.
export const BAKE_OFF_SQUARES: readonly string[] = [
  'Paul Holly\u00ADwood handshake',
  '"Soggy bottom"',
  'Under\u00ADbaked in the middle',
  'Over\u00ADproofed bread',
  "Some\u00ADone's bake collapses",
  'Ice cream melts in the heat',
  'Ingre\u00ADdients in the bin',
  'Last-second decorating',
  '"Ten minutes left, bakers!"',
  'Mid-bake hug from a host',
  'Squirrel cutaway',
  'Sheep in a field',
  'Rain on the tent roof',
  'Mystery technical instructions',
  '"It\'s a bit dry"',
  '"Good bake"',
  'A pun about the theme',
  'Bunting in shot',
  'Fridge-door stand-off',
  'Someone sets a timer, forgets it',
  "Some\u00ADone's showstopper leans",
  'Col\u00ADlapsing tower of choux',
  'Someone cries in the tent',
  'Star Baker reveal',
  '"Lovely flavours"',
  'Anxious oven-peering',
  'Temper\u00ADing chocolate drama',
  "Custard won't set",
  'Someone uses a family recipe',
  'Biscuit snaps on cue',
  'A bake looks like a face',
  'Bread week',
  "Some\u00ADone's mum's recipe",
  'Diagrams of the bakes',
  '"Who made this?" technical reveal',
  'Last place in the technical',
  'Gelatine goes wrong',
  'Raw pastry',
  'Someone runs out of time',
  'Sugar work shatters',
  'Elab\u00ADorate theme idea',
  "Some\u00ADone's job mentioned",
  'Ice bath for a bake',
  'Burnt caramel',
  'A flavour combo raises eyebrows',
  'Someone drops something',
  '"Ready, set, bake!"',
  'Hug after an elimination',
  'Too much decoration',
];
