// Bingo squares for The Celebrity Traitors. Order matters: cards reference squares by index,
// so only append or edit in place while rooms are live; reordering is safe between episodes.
// Soft hyphens (\u00AD) mark break points in long capitalised words, which browsers won't auto-hyphenate.
export const CELEBRITY_TRAITORS_SQUARES: readonly string[] = [
  'Claudia wears a statement knit',
  'Claudia does the fringe flick',
  'Someone says "I\'m 100% Faithful"',
  '"I swear on my children\'s lives"',
  'A Faithful votes for a Faithful',
  'Someone cries at the round table',
  'Dramatic slow walk to breakfast',
  'Empty chair at breakfast gasp',
  'A Traitor fakes shock at a murder',
  '"I\'ve got a gut feeling"',
  'Accused of being too quiet',
  'Accused of being too loud',
  'Cloaks swishing in the turret',
  'Murder letter read aloud',
  'Shield won in a mission',
  'Someone hides a shield',
  'Mission involves heights',
  'Mission involves something buried',
  'Mission in the dark',
  'A coffin appears',
  'Bagpipes',
  'Drone shot of the castle',
  'Highland cow cameo',
  'Rain lashes the windows',
  '"It\'s time to murder"',
  'Recruit\u00ADment offer',
  'Ultimatum recruitment',
  '"I am a Faithful" at banishment',
  'Banished player reveals Traitor',
  'Vote ends in a tie',
  'A last-second vote change',
  'Whis\u00ADpered chat by the fire',
  'Celeb mentions their day job',
  'Celeb name-drops a famous mate',
  'Someone forgets a name',
  '"You\'re playing a blinder"',
  'Gin or whisky in hand',
  'Someone hugs a suspect',
  'Pointing across the table',
  '"Hear me out…"',
  '"I\'m just being honest"',
  'Someone stands up to speak',
  'Accu\u00ADsation based on body language',
  'Prize pot goes up',
  'Prize pot money lost',
  'Ominous music sting',
  'Claudia says "deliciously"',
  'Claudia laughs at her own joke',
  '"Game face" gets mentioned',
  'Traitor betrays a Traitor',
  'Bedroom confessional in pyjamas',
  'Cut to a raven or crow',
  "Celeb admits they can't lie",
  '"The Traitors are clever"',
];
