// Bingo squares for Dancing on Ice. Order matters: cards reference squares by index,
// so only append or edit in place while rooms are live; reordering is safe between episodes.
// Soft hyphens (\u00AD) mark break points in long capitalised words, which browsers won't auto-hyphenate.
export const DANCING_ON_ICE_SQUARES: readonly string[] = [
  'Someone falls on the ice',
  'Spin goes wobbly',
  '"Bolero" mentioned',
  'Head\u00ADbanger move',
  'Lift goes wrong',
  'Toe-pick trip',
  'Skating partner rescue',
  'Live music cue',
  'Costume glitters under the lights',
  'Dry ice smoke',
  'Training rink footage',
  'Celeb talks about nerves',
  '"They\'ve come so far"',
  'Skate-off',
  'Judges disagree',
  'A perfect score',
  'Low score shock',
  'Pro skater solo',
  'Group routine',
  'Ice gets resurfaced',
  'Someone grabs the barrier',
  'Crowd cheers a recovery',
  'A celeb was injured in training',
  'Profes\u00ADsional catches a fall',
  'Backflip or big trick',
  'Celeb cries at the scores',
  'Theme week costume',
  'Family in the audience',
  'Phone lines plug',
  'Slow-mo replay of a wobble',
  '"Edges!" note from a judge',
  'Pairs spin',
  'Spot\u00ADlight on the ice',
  'Applause for a lift',
  'Someone skates out of time',
  'Ice-cold catchphrase pun',
  "Last week's scores recap",
  'Skating boots close-up',
  'A pirouette',
  '"I never thought I\'d do this"',
  'Jumps get a gasp',
  'Big finale pose',
  'Hug at the barrier',
  'A celeb blows a kiss',
  'Pro and celeb in matching outfits',
  'Com\u00ADmentary on posture',
  '"Head up!" note',
  'Standing ovation',
];
