// Bingo squares for I'm a Celebrity… Get Me Out of Here!. Order matters: cards reference squares by index,
// so only append or edit in place while rooms are live; reordering is safe between episodes.
// Soft hyphens (\u00AD) mark break points in long capitalised words, which browsers won't auto-hyphenate.
export const IM_A_CELEB_SQUARES: readonly string[] = [
  '"Get me out of here!"',
  'Bush\u00ADtucker trial',
  'Trial with eyeballs or offal',
  'Snakes in a box',
  'Someone wins every star',
  'Zero stars',
  'Rice and beans again',
  'Tears over a letter from home',
  'Hammock wobble',
  'Dunny cam confession',
  'Rain floods the camp',
  'A fight over the washing up',
  'Someone takes charge of cooking',
  'Campfire singalong',
  'Spider crawls on a sleeper',
  'Celeb\u00ADrity chest challenge',
  '"Is it a yes or a no?"',
  'Ant and Dec pun',
  'Ant and Dec in matching outfits',
  'Someone screams before it starts',
  'Late arrivals crash the camp',
  'Camp leader election',
  'Someone refuses to do a trial',
  'A celeb mentions their comeback',
  'Jungle telegram',
  'Gossip at the waterhole',
  'Someone sunbathes in a hat',
  'Bird or bug close-up',
  'Jungle Pop or treat reward',
  'Phone lines plug',
  'Someone is first out',
  'Tears at the campfire',
  'Someone talks about weight loss',
  'Hunger complaint',
  'A celeb does an impression',
  "A celeb's catchphrase",
  'Slop gets thrown',
  'Someone sleeps through an alarm',
  'Two celebs clash',
  'Kitchen rota drama',
  'Night-vision camera shot',
  'Someone counts the days',
  '"Never done anything like this"',
  'Hugging after a trial',
  "A celeb's luggage item",
  '"I\'m here to show the real me"',
  'Snake handler appears',
  'A kangaroo or croc cameo',
];
