// Bingo squares for Strictly Come Dancing. Order matters: cards reference squares by index,
// so only append or edit in place while rooms are live; reordering is safe between episodes.
// Soft hyphens (\u00AD) mark break points in long capitalised words, which browsers won't auto-hyphenate.
export const STRICTLY_SQUARES: readonly string[] = [
  'Craig says "a-ma-zing"',
  'Craig says "disaster, darling"',
  'Craig gives a 2',
  'Booed by the audience',
  'Shirley says "fabulous"',
  'Shirley points at the camera',
  "Motsi's big reaction",
  'Anton mentions "the ballroom"',
  'First 10 of the night',
  'Someone says "the journey"',
  'Training montage includes tears',
  'Pro does a dramatic lift',
  'Illegal lift mentioned',
  'Hip action critiqued',
  'Feet were flat / "toes!"',
  'Someone loses their shoe',
  'Wardrobe malfunction',
  'Fake tan comment',
  'Sequins close-up',
  'Feathers everywhere',
  'Paso Doble with a cape',
  "Couple's Choice with a big story",
  'Argen\u00ADtine Tango gasp moment',
  'Quick\u00ADstep "full of energy"',
  'Rumba "lacked chemistry"',
  'Charles\u00ADton with jazz hands',
  'Dance off mentioned',
  '"Keep dancing!"',
  'Group hug waiting for the scores',
  'Celeb says "I never thought I\'d…"',
  'Dance dedicated to a relative',
  "Celeb's family in the audience",
  'Pro dancer group number',
  'Band plays a pop song as a waltz',
  'Judges disagree loudly',
  'Head judge has the casting vote',
  '"Black\u00ADpool" mentioned',
  '"The Strictly curse" hinted',
  'Training room sweat shot',
  'Partner swap rumour joke',
  'Someone forgets the routine',
  'Out of time with the music',
  'Standing ovation',
  'Audience chants a name',
  'Leader\u00ADboard reveal gasp',
  'Phone lines plug',
  "Last week's scores flashback",
  'Glitter\u00ADball shot',
  'Spray-tan or hairspray cloud',
  'A dip at the end goes wrong',
  'Celeb out of breath at the desk',
  '"Seven!"',
];
