// Bingo squares for The Traitors. Order matters: cards reference squares by index,
// so only append or edit in place while rooms are live; reordering is safe between episodes.
// Soft hyphens (\u00AD) mark break points in long capitalised words, which browsers won't auto-hyphenate.
export const TRAITORS_SQUARES: readonly string[] = [
  "Claudia's statement knitwear",
  'Claudia does the fringe flick',
  'Someone says "I\'m 100% Faithful"',
  'Someone mentions their day job',
  '"I\'m doing this for my family"',
  'A Faithful votes out a Faithful',
  'Tears at the round table',
  'Dramatic slow walk to breakfast',
  'Empty chair at breakfast',
  'A Traitor fakes shock at a murder',
  '"I\'ve got a gut feeling"',
  'Accused of being too quiet',
  'Accused of playing too hard',
  'Cloaks swishing in the turret',
  'Murder in plain sight',
  'Shield won in a mission',
  'Someone hides their shield',
  'Mission involves heights',
  'Mission involves being buried',
  'A coffin appears',
  'Bagpipes',
  'Drone shot of the castle',
  'Rain lashes the windows',
  'Recruit\u00ADment by letter',
  'Ultimatum recruitment',
  '"I am a Faithful" at banishment',
  'Banished player reveals Traitor',
  'Vote ends in a tie',
  'Someone changes their vote',
  'Whis\u00ADpered chat by the fire',
  '"Hear me out…"',
  '"I\'m just being honest"',
  'Someone stands up to speak',
  'Accu\u00ADsation based on body language',
  'Prize pot goes up',
  'Prize pot money lost',
  'Ominous music sting',
  'Traitor betrays a Traitor',
  'Bedroom confessional',
  'Cut to a raven or crow',
  '"I\'m a terrible liar"',
  'A slate read out very slowly',
  'Hugs after the banishment',
  'A Faithful cries over a murder',
  'Someone eats alone',
  'Claudia says "deliciously"',
  'Group huddles in the library',
  'A pact is made',
  'A pact is broken',
  'Someone\'s "gut" is wrong again',
];
